# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoIDNow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoIDNow
	pod 'IDnowSDK'

  target 'DemoIDNowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoIDNowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoIDNow2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoIDNow2
	pod 'IDnowSDK'

end
